Employees:
  1:
    Address: Eppingen
    Country: Germany
    Email: maximilian.wolf@ibsolution.com
    First Name: Maximilian
    Job: IT
    Joining the company: 01.08.2024
    Last Name: Wolf
    Pay: '800'
    Pension start date: 01.08.2024
    Position: IT_Admin
    Telephone: '015225446050'
